# Generated by Django 4.2.4 on 2023-12-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_customfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.CharField(max_length=255)),
                ('column3', models.CharField(max_length=255)),
                ('column4', models.CharField(max_length=255)),
                ('column5', models.CharField(max_length=255)),
                ('column6', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomFile',
        ),
    ]
